version: '3'
services:
  latex-generator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./artifacts/docker/input:/artifacts/input
      - ./artifacts/docker/output:/artifacts/output
